language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull grgrlmml/overpass-api:TEST
  - docker run -d -p 9090:9090 evacuation-web-app/overpass-api:TEST

script:
  - cd ${TRAVIS_BUILD_DIR} && mvn test
