language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull grgrlmml/overpass-api-4-tests
  - docker run -d -p 9090:9090 grgrlmml/overpass-api-4-tests

script:
  - cd ${TRAVIS_BUILD_DIR} && mvn test
